include 7-vars.fs
include 7.fs

uglvj  ymfjt parent!
uglvj  gkpgf parent!
xhymdo  errip parent!
xhymdo  lsppdni parent!
xhymdo  mxukll parent!
ubvvr  hrpzu parent!
ubvvr  msjeeks parent!
ubvvr  ozizlok parent!
zfotzg  ovomgd parent!
zfotzg  mqhwlq parent!
yierd  ubnxkza parent!
yierd  whlsvf parent!
yierd  pnnpym parent!
yierd  tznsg parent!
yciccp  ijpsv parent!
yciccp  fjtafl parent!
yciccp  lxwntcm parent!
yciccp  saacvs parent!
boxtod  sxtbzfe parent!
boxtod  etdah parent!
iceaj  zbqgiy parent!
iceaj  taxdaf parent!
yikzq  yhrnh parent!
yikzq  yipnm parent!
aqksi  olotqeb parent!
aqksi  vioyx parent!
dgehtvc  sxwcr parent!
dgehtvc  usfkacz parent!
cwoyko  uycwnb parent!
cwoyko  pttvms parent!
cwoyko  ingae parent!
cwoyko  tedoj parent!
iejyzgu  lgnfrti parent!
iejyzgu  lomvf parent!
gmpoe  gpxhd parent!
gmpoe  deylq parent!
yhxkh  vyabn parent!
yhxkh  xtwaov parent!
ugeudg  dxffsoq parent!
ugeudg  nyzvofv parent!
ugeudg  tvrosaa parent!
ugeudg  nmojt parent!
wfuoll  cciwzc parent!
wfuoll  qpafkjx parent!
wfuoll  axlitg parent!
xvpopw  wkhzk parent!
xvpopw  zlnks parent!
jtejd  fzklxq parent!
jtejd  jrbqu parent!
jtejd  qhxns parent!
jtejd  lerqv parent!
ffizjl  szeszcp parent!
ffizjl  wgmvio parent!
bmwankt  tdmok parent!
bmwankt  ygkwtl parent!
bmwankt  sgose parent!
bmwankt  uohurz parent!
xjsyk  zhjzpaa parent!
xjsyk  qylvdk parent!
pfyexc  zzqjykw parent!
pfyexc  alflnz parent!
pohqjzd  qltdz parent!
pohqjzd  ppzlmxg parent!
jpvyg  lhbmgxc parent!
jpvyg  qtxkvx parent!
jpvyg  kynyas parent!
jpvyg  easamud parent!
snxgfl  ypufgmt parent!
snxgfl  qvtwlq parent!
ddkhuyg  alywuv parent!
ddkhuyg  nvdoenr parent!
ddkhuyg  mnyng parent!
ddkhuyg  rhsztrd parent!
comyzns  fcmnfq parent!
comyzns  nrzhlvo parent!
nfbcs  vzpkp parent!
nfbcs  wmfydk parent!
tiwxhoa  wfnox parent!
tiwxhoa  bwdijxn parent!
indhpfx  umlbvg parent!
indhpfx  fjdki parent!
indhpfx  ctjygk parent!
dlluqgz  asdbbxb parent!
dlluqgz  vfetz parent!
lgtpuqr  cdooel parent!
lgtpuqr  eozsgq parent!
lgtpuqr  dfsas parent!
lgtpuqr  ldbwwt parent!
ythoww  alqkr parent!
ythoww  qicxdmg parent!
ykshd  qufymlj parent!
ykshd  simlhnw parent!
ykshd  kjljvr parent!
bqzfjn  txywrwk parent!
bqzfjn  tpvcmkz parent!
bqzfjn  fklkig parent!
bqzfjn  katovn parent!
bqzfjn  jgckfb parent!
bqzfjn  vwqquk parent!
zdljb  wviisf parent!
zdljb  zhavocr parent!
sqdhc  cwoyko parent!
sqdhc  pfyexc parent!
sqdhc  mdyhk parent!
sqdhc  zscqv parent!
sqdhc  eqpuq parent!
sqdhc  zspohe parent!
zznkz  vyybi parent!
zznkz  sblacv parent!
gqmls  fqvvrgx parent!
gqmls  szmnwnx parent!
gqmls  jfdck parent!
oprsej  rpijkf parent!
oprsej  wtosgg parent!
hlkvwq  wiqpx parent!
hlkvwq  bhxtgro parent!
kzeubgd  wwritm parent!
kzeubgd  wrcpxdx parent!
kzeubgd  kxouhtb parent!
hughxts  asxiywb parent!
hughxts  dzwnzm parent!
kvvjhrt  zsajqjv parent!
kvvjhrt  nvcmjx parent!
kvvjhrt  qczgjc parent!
yftqma  fewgbm parent!
yftqma  cukwe parent!
katovn  ffizjl parent!
katovn  ondvq parent!
katovn  nbbctar parent!
katovn  aonrg parent!
rrrxeic  gwwxkxx parent!
rrrxeic  aeljb parent!
vuldvce  mdoyb parent!
vuldvce  hukfj parent!
uwaxli  ortan parent!
uwaxli  hlglt parent!
uwaxli  oivlxe parent!
uwaxli  eilfrxc parent!
igiqnkc  idjugav parent!
igiqnkc  cwkqb parent!
syrnxgz  flzcf parent!
syrnxgz  rblzgyw parent!
syrnxgz  yzkzx parent!
klkodi  edyfj parent!
klkodi  wtsesxe parent!
enswibe  hlsoglk parent!
enswibe  nkpzu parent!
cjxuj  gtjgxiw parent!
cjxuj  wxksnf parent!
owprin  komav parent!
owprin  zzdvozt parent!
owprin  eordj parent!
bymyuke  dadlbnn parent!
bymyuke  htwkr parent!
bymyuke  dlluqgz parent!
arjsnz  rwrusdg parent!
arjsnz  krgdzw parent!
arjsnz  olhbx parent!
ghebwaz  xxqwea parent!
ghebwaz  lybjgk parent!
obbei  jsuevqz parent!
obbei  hxsuo parent!
rdihhfv  ozjka parent!
rdihhfv  mskbq parent!
rdihhfv  qrpis parent!
rdihhfv  dqury parent!
hhdth  ylixmj parent!
hhdth  ukgzz parent!
ocmuu  pbjuhpo parent!
ocmuu  ovlbvyj parent!
sxbee  fplzsya parent!
sxbee  yftqma parent!
sxbee  hweub parent!
sxbee  yhxkh parent!
sxbee  xhymdo parent!
sxbee  cafxx parent!
ylfgaps  tzbreu parent!
ylfgaps  izxgcf parent!
qzzhap  uhyboog parent!
qzzhap  nzlhfa parent!
mskbq  hqwdr parent!
mskbq  askqu parent!
crlgf  cxqdrz parent!
crlgf  kjtdypr parent!
sjyso  usbjn parent!
sjyso  puuwu parent!
wustjt  quinb parent!
wustjt  sqdhc parent!
wustjt  kcekden parent!
rlsnxvu  xdkin parent!
rlsnxvu  wnvmb parent!
rlsnxvu  tfrjlk parent!
wnmbn  egoezf parent!
wnmbn  nodgjd parent!
wnmbn  vrrmn parent!
wnmbn  uicpy parent!
nnoaqvv  isixko parent!
nnoaqvv  frklhh parent!
nnoaqvv  ugeudg parent!
ylmixxx  ewycyf parent!
ylmixxx  iddby parent!
pqjrycz  urjsyac parent!
pqjrycz  olwudc parent!
pqjrycz  ezntvw parent!
pqjrycz  gpktinr parent!
igrih  cdahg parent!
igrih  vqpkne parent!
ifajhb  thuzqqo parent!
ifajhb  fwlspf parent!
ifajhb  mhfci parent!
ifajhb  bbeclr parent!
ifajhb  arjsnz parent!
hipirzc  vpmtex parent!
hipirzc  hhzjn parent!
hipirzc  oilsjpr parent!
hipirzc  mpxfrig parent!
hipirzc  geibkdq parent!
hipirzc  xzjdfbr parent!
mqgculh  yvchtk parent!
mqgculh  zmiee parent!
msjeeks  tqclz parent!
msjeeks  fjayhh parent!
jgckfb  bcjpkwf parent!
jgckfb  ungcoot parent!
jgckfb  mzhyo parent!
jgckfb  iwcpvdx parent!
jgckfb  dvuug parent!
wdycxsw  gzokm parent!
wdycxsw  yqpxoki parent!
tcclaa  wdblza parent!
tcclaa  vfdnvk parent!
jzjxhyw  krovuvc parent!
jzjxhyw  brolhd parent!
ixlern  llzodgr parent!
ixlern  hwdtq parent!
ahuboc  jkszke parent!
ahuboc  lpxleg parent!
xwmjpb  eqxumuo parent!
xwmjpb  xmbafj parent!
gqzczp  bzapqu parent!
gqzczp  dismcam parent!
zwaky  dqcxe parent!
zwaky  ojyssxz parent!
vjvjnc  hoyipx parent!
vjvjnc  qoxsu parent!
vjvjnc  comyzns parent!
hrpzu  rlhqosc parent!
hrpzu  bryevj parent!
kndpli  gegrzz parent!
kndpli  vandhv parent!
ovvmrux  ulvoyev parent!
ovvmrux  lgkrhh parent!
zjxspcp  tiwxhoa parent!
zjxspcp  pqjrycz parent!
zjxspcp  sdstw parent!
cczfm  pnghx parent!
cczfm  tusimd parent!
cczfm  putdqt parent!
cczfm  sbcyifk parent!
cczfm  uxblgk parent!
alywuv  mlhga parent!
alywuv  odzzie parent!
alywuv  awddb parent!
alywuv  koxzwq parent!
alywuv  cczfm parent!
alywuv  hipirzc parent!
alywuv  qqktjg parent!
corqny  crlgf parent!
corqny  xkfuz parent!
corqny  gzoyqay parent!
corqny  cakpt parent!
atkstsn  kntyjf parent!
atkstsn  hwcwcn parent!
jfdck  marnqj parent!
jfdck  moxiw parent!
jfdck  sxijke parent!
jfdck  ojgdow parent!
jfdck  fnlapoh parent!
afjqx  unokgle parent!
afjqx  bwsvr parent!
upair  xfxqbqv parent!
upair  svdlp parent!
upair  hqget parent!
sdstw  czgov parent!
sdstw  tgrtt parent!
ymrfvp  veplkeo parent!
ymrfvp  iouamne parent!
wxakaqf  xnpbhpt parent!
wxakaqf  liwwgd parent!
qigsvd  gmpoe parent!
qigsvd  ymqmr parent!
qigsvd  wdycxsw parent!
qigsvd  ixszebq parent!
fafvyk  egjsilp parent!
fafvyk  usodp parent!
myhfh  howpl parent!
myhfh  upvrm parent!
myhfh  xjsyk parent!
bzjze  wsjuynd parent!
bzjze  aicwnq parent!
bzjze  fixbeu parent!
zgmrmd  sebtdcx parent!
zgmrmd  nmfsbu parent!
ruxqapz  xhhtjwu parent!
ruxqapz  xhirm parent!
txywrwk  lbflpug parent!
txywrwk  indhpfx parent!
txywrwk  sxcxmg parent!
uohmo  zznkz parent!
uohmo  ustkg parent!
uohmo  stflbsr parent!
uohmo  qzeljtb parent!
moxiw  cqtkhqi parent!
moxiw  pohqjzd parent!
moxiw  oagvuu parent!
moxiw  nfbcs parent!
moxiw  hughxts parent!
moxiw  kvvjhrt parent!
moxiw  qzzhap parent!
oywnenv  fhlbjvx parent!
oywnenv  joyncgz parent!
pnghx  wktjf parent!
pnghx  umyqf parent!
uosltv  wxmxkzn parent!
uosltv  xvgcls parent!
elxydx  orpzr parent!
elxydx  nddekdg parent!
chpjfv  psyino parent!
chpjfv  hivoik parent!
chpjfv  qhqbqj parent!
chpjfv  qzuirrb parent!
abmlupq  fcpejj parent!
abmlupq  qgiijpu parent!
abmlupq  iolil parent!
abmlupq  khdgj parent!
qfitmrm  tmgoed parent!
qfitmrm  gkhrgd parent!
qfitmrm  zjzkwxq parent!
qfitmrm  bjcthpx parent!
qoxsu  qzoas parent!
qoxsu  jedlbro parent!
koxzwq  geuopn parent!
koxzwq  ransdtt parent!
koxzwq  bmwankt parent!
koxzwq  qmdbgke parent!
sqauq  paquh parent!
sqauq  goaazlt parent!
walei  wipafb parent!
walei  rzpxffj parent!
yzvvyb  eyiiwv parent!
yzvvyb  awaoi parent!
uspzk  idcgo parent!
uspzk  etevb parent!
xdkin  gkzbah parent!
xdkin  cxgxbo parent!
xdkin  jdvbztj parent!
xdkin  mviyuy parent!
rtngius  boxtod parent!
rtngius  wpwlg parent!
rtngius  igrih parent!
rtngius  tgxuhxp parent!
rtngius  iceaj parent!
rtngius  kqecnz parent!
dgoocsw  ifajhb parent!
dgoocsw  gqmls parent!
dgoocsw  sgmbw parent!
dgoocsw  ddkhuyg parent!
dgoocsw  rhqocy parent!
wsrmfr  optohy parent!
wsrmfr  tcxwrcv parent!
wsrmfr  wbckbcz parent!
wnvmb  hhivpic parent!
wnvmb  pikqy parent!
unllgjg  dgeseao parent!
unllgjg  vobnuq parent!
isixko  kkuzi parent!
isixko  ssdpo parent!
uqgco  uwuouhv parent!
uqgco  ocmuu parent!
uqgco  uvogit parent!
uqgco  mvwcdq parent!
uqgco  errrzm parent!
uqgco  mynuy parent!
xmhil  wloqry parent!
xmhil  gzrmt parent!
xmhil  gmktbew parent!
howpl  qlkhbf parent!
howpl  rnqtg parent!
ransdtt  suriq parent!
ransdtt  vqbaw parent!
szmnwnx  mgayiu parent!
szmnwnx  nnoaqvv parent!
szmnwnx  kupsxf parent!
szmnwnx  rlsnxvu parent!
gvtnin  awgucd parent!
gvtnin  krqff parent!
gvtnin  ipruxk parent!
fvtmh  neltlwg parent!
fvtmh  irzscv parent!
mnyng  plvjk parent!
mnyng  vjvjnc parent!
mnyng  clxlfgu parent!
emsacsk  jcekn parent!
emsacsk  tcawlkc parent!
mlhga  qfitmrm parent!
mlhga  enswibe parent!
mlhga  tefmun parent!
mlhga  qshflsm parent!
mlhga  vcgyi parent!
mlhga  oywnenv parent!
dapjjl  pbxzzdi parent!
dapjjl  elxydx parent!
dapjjl  ghlkk parent!
dapjjl  rnjqmh parent!
dapjjl  dgehtvc parent!
dapjjl  aqksi parent!
nodgjd  feygolx parent!
nodgjd  mtgsssx parent!
plevjup  kmcjs parent!
plevjup  vtwtgf parent!
fqvvrgx  xmhil parent!
fqvvrgx  dbzwyez parent!
fqvvrgx  bmhlcgg parent!
jlsxjq  zanpviw parent!
jlsxjq  xcrmvq parent!
kbjpgv  atzcjm parent!
kbjpgv  vldxx parent!
awddb  npsuo parent!
awddb  rrrxeic parent!
awddb  fhyfd parent!
aonrg  fyqlzxt parent!
aonrg  ehhlvc parent!
aonrg  bpzwq parent!
aonrg  qeoicwx parent!
krzuab  jtxsofx parent!
krzuab  xrockzz parent!
zwwrwfy  fquyicp parent!
zwwrwfy  sbxkokp parent!
zwwrwfy  corqny parent!
zwwrwfy  kzeubgd parent!
yjlzpv  jshaf parent!
yjlzpv  vzpwamg parent!
fhyfd  tevxh parent!
fhyfd  cpphf parent!
mgayiu  ksvdw parent!
mgayiu  euueza parent!
mgayiu  txfnjo parent!
mgayiu  bhtwp parent!
mgayiu  pvnjsr parent!
tgqnyb  rtngius parent!
tgqnyb  uqgco parent!
tgqnyb  zjxspcp parent!
ixszebq  atfgzcb parent!
ixszebq  fjdvux parent!
whgqhb  nqehtaf parent!
whgqhb  wnshgr parent!
whgqhb  wfuoll parent!
whgqhb  cmnjg parent!
whgqhb  olqgu parent!
uwuouhv  pwguzgm parent!
uwuouhv  krbsvt parent!
ogpunov  eqsrff parent!
ogpunov  uwaxli parent!
ogpunov  tszcogp parent!
ogpunov  zgmrmd parent!
ogpunov  wugret parent!
ogpunov  zdljb parent!
egoezf  kmoov parent!
egoezf  hgyelhc parent!
geibkdq  oaqtjz parent!
geibkdq  nwcbnxq parent!
ouxdvp  gbrqt parent!
ouxdvp  edncj parent!
isbppt  rkgvdhv parent!
isbppt  hwvnv parent!
bajtat  wsqlsgl parent!
bajtat  ykohs parent!
ondvq  wthxapy parent!
ondvq  vqghnm parent!
fzerj  feuirvn parent!
fzerj  rklic parent!
fzerj  vxbzw parent!
fzerj  rzvrn parent!
xykcof  ptmqqpk parent!
xykcof  zfotzg parent!
xykcof  jfhqmi parent!
xykcof  kivlu parent!
xykcof  vvkgsba parent!
dlzlo  viantn parent!
dlzlo  ymjxuy parent!
dlzlo  vimzk parent!
krgdzw  oxvcp parent!
krgdzw  sdllj parent!
krgdzw  jtejd parent!
krgdzw  fjiemrs parent!
krgdzw  gvtnin parent!
krgdzw  dfnijm parent!
krgdzw  yzvvyb parent!
oagvuu  heuuqx parent!
oagvuu  meqbgw parent!
mpxfrig  elhjwu parent!
mpxfrig  cokjdc parent!
mpxfrig  rvzjawx parent!
etdmt  emsacsk parent!
etdmt  emvml parent!
etdmt  egcyvrv parent!
etdmt  srjbcye parent!
etdmt  ffyfj parent!
etdmt  ahuboc parent!
psblh  kfhcuvf parent!
psblh  uspzk parent!
psblh  wxakaqf parent!
futsmzx  efehrqd parent!
futsmzx  hmfyf parent!
futsmzx  pgmnqws parent!
hhzjn  npmafis parent!
hhzjn  ppkxgj parent!
qufymlj  bbvrbl parent!
qufymlj  ainqphn parent!
zscqv  acvrb parent!
zscqv  ggplfue parent!
zscqv  iygtv parent!
marnqj  upair parent!
marnqj  mkrrlbv parent!
marnqj  vqkwlq parent!
marnqj  wsrmfr parent!
ssbjh  vfzlh parent!
ssbjh  tdrsmxa parent!
dadlbnn  qrpab parent!
dadlbnn  jejvld parent!
ymqmr  xcqhk parent!
ymqmr  yxcliv parent!
ymqmr  dubsgvx parent!
ymqmr  kuhyqad parent!
kxpffcy  cqdkb parent!
kxpffcy  hcetpw parent!
kxpffcy  yqkwau parent!
fwxtdml  wfzbtxa parent!
fwxtdml  mygjnz parent!
fwxtdml  pqeph parent!
dbzwyez  mcvws parent!
dbzwyez  kocwei parent!
dbzwyez  lurly parent!
dbzwyez  xdraxfj parent!
jipgo  qgptpig parent!
jipgo  klkodi parent!
jipgo  tcclaa parent!
jdfrbhy  sgrwrkz parent!
jdfrbhy  czfza parent!
jdfrbhy  ymheeao parent!
jdfrbhy  ucqru parent!
thuzqqo  dapjjl parent!
thuzqqo  lvbjtf parent!
thuzqqo  bijhyzu parent!
mmdrry  gwgdt parent!
mmdrry  hiwslh parent!
mmdrry  erjcx parent!
mmdrry  mqccum parent!
sfbpnnz  cwrllq parent!
sfbpnnz  evgupeo parent!
qmdbgke  ttbtij parent!
qmdbgke  cpwxm parent!
emvml  vipgc parent!
emvml  gpkltyi parent!
pbxzzdi  rgonoq parent!
pbxzzdi  zsnenc parent!
pbxzzdi  zwxjsev parent!
pbxzzdi  dyamtle parent!
sbxkokp  gxzgsaa parent!
sbxkokp  sjyso parent!
sbxkokp  snxgfl parent!
sbxkokp  unllgjg parent!
jmazezm  grrbzan parent!
jmazezm  hxnnsp parent!
jmazezm  etgjaum parent!
jmazezm  wccpr parent!
tusimd  rfrgmgz parent!
tusimd  mbsaywb parent!
upvrm  effjvcu parent!
upvrm  uwrqxmj parent!
bhtwp  scqhs parent!
bhtwp  sixicw parent!
bhtwp  mgghj parent!
bqfsjz  ldwogg parent!
bqfsjz  mbvjj parent!
sxijke  dlzlo parent!
sxijke  jlsxjq parent!
sxijke  jmazezm parent!
fquyicp  fudpn parent!
fquyicp  sfbpnnz parent!
fquyicp  ymrfvp parent!
fquyicp  fyptb parent!
dfnijm  saxamw parent!
dfnijm  sgwcf parent!
dfnijm  wlefwf parent!
dfnijm  dcibpv parent!
foldo  skyucv parent!
foldo  ncunr parent!
gvzze  mupwbp parent!
gvzze  qowagej parent!
ungcoot  ejijju parent!
ungcoot  gldkli parent!
pvnjsr  tedjgv parent!
pvnjsr  vpemk parent!
pvnjsr  lijnzj parent!
pvnjsr  ohprzku parent!
ryrtqj  fvtxd parent!
ryrtqj  vuknf parent!
ryrtqj  dhhpxsj parent!
hoyipx  rpqvli parent!
hoyipx  ixrrfy parent!
ytbnpd  rdihhfv parent!
ytbnpd  ctdey parent!
ytbnpd  vetgu parent!
ytbnpd  bymyuke parent!
ytbnpd  ogpunov parent!
ytbnpd  uohmo parent!
feuirvn  yjlzpv parent!
feuirvn  mibwe parent!
feuirvn  hlkvwq parent!
feuirvn  ufses parent!
feuirvn  jpvyg parent!
feuirvn  auzdz parent!
feuirvn  futsmzx parent!
srjbcye  xvtwfks parent!
srjbcye  skwbfku parent!
srjbcye  qnqwt parent!
srjbcye  awsdwry parent!
tszcogp  abzdsbs parent!
tszcogp  qrjor parent!
ksvwjw  pcuxhb parent!
ksvwjw  zigfjrn parent!
klvncy  slqmpe parent!
klvncy  kbyrlz parent!
klvncy  xzjiiwl parent!
ilsqjz  nqkpd parent!
ilsqjz  grkyj parent!
ksvdw  sskog parent!
ksvdw  xettl parent!
wpwlg  kuxclnz parent!
wpwlg  fkagf parent!
xiksvn  cklbsi parent!
xiksvn  ydhrzjf parent!
clxlfgu  yciccp parent!
clxlfgu  lhhlg parent!
clxlfgu  zwaky parent!
clxlfgu  kbjpgv parent!
clxlfgu  vuldvce parent!
clxlfgu  jzjxhyw parent!
clxlfgu  crxuc parent!
zqkgqs  obvvk parent!
zqkgqs  ejkxeg parent!
ufses  jjwpqn parent!
ufses  rnhom parent!
jdvfkii  qdibw parent!
jdvfkii  fthyzq parent!
jdvfkii  kdcijis parent!
rhsztrd  etdmt parent!
rhsztrd  ykshd parent!
rhsztrd  xykcof parent!
fklkig  ykcmvla parent!
fklkig  owhxvku parent!
fklkig  yrdpurl parent!
yxljri  ttfdct parent!
yxljri  jshxbra parent!
fmvdadz  opqpgol parent!
fmvdadz  bryrofn parent!
ygbecwq  mjvopd parent!
ygbecwq  midqcpz parent!
xzjdfbr  jjwadjm parent!
xzjdfbr  tkpcmi parent!
fqqzx  fafvyk parent!
fqqzx  syrnxgz parent!
fqqzx  xofjd parent!
dvuug  nxtmr parent!
dvuug  emdtn parent!
xxiymn  ryrtqj parent!
xxiymn  yikzq parent!
xxiymn  fvtmh parent!
xxiymn  bqfsjz parent!
xxiymn  lgtpuqr parent!
xxiymn  diila parent!
ffyfj  nepmits parent!
ffyfj  sqcodst parent!
kdmuzrx  efhuz parent!
kdmuzrx  yziwzua parent!
kdmuzrx  wxnoy parent!
kdmuzrx  kbgfqwc parent!
coxtcw  jdfrbhy parent!
coxtcw  orulm parent!
coxtcw  xiksvn parent!
fudpn  nldgsz parent!
fudpn  oluzb parent!
ozizlok  kfohhmp parent!
ozizlok  dlqmd parent!
ozizlok  zbbdyc parent!
ozizlok  qlrcubm parent!
htwkr  rhifo parent!
htwkr  xybhge parent!
htwkr  slhmny parent!
ocobkpo  yquhjrb parent!
ocobkpo  akmjes parent!
frklhh  qfanlc parent!
frklhh  ouuud parent!
frklhh  gamlcl parent!
frklhh  chlyf parent!
nqehtaf  vkmtnn parent!
nqehtaf  iouczne parent!
nqehtaf  krzuab parent!
nqehtaf  mmdrry parent!
bbeclr  zwqgf parent!
bbeclr  wnmbn parent!
bbeclr  jipgo parent!
ompzpgp  uemklxf parent!
ompzpgp  vwltm parent!
adwzzi  yirmii parent!
adwzzi  pptok parent!
adwzzi  iqcjr parent!
adwzzi  uhuieb parent!
fplzsya  ifdeve parent!
fplzsya  sdiyd parent!
qrpis  srbczq parent!
qrpis  efajqe parent!
qrpis  qdxvydf parent!
wohob  drdvm parent!
wohob  mdbzm parent!
wohob  bmswiwx parent!
wohob  fjuudqb parent!
lbflpug  mgqfs parent!
lbflpug  bpknup parent!
lbflpug  qxubki parent!
lbflpug  bbijzr parent!
quinb  jnojpf parent!
quinb  qtzor parent!
xkfuz  rzned parent!
xkfuz  eyqkgna parent!
xkfuz  vjeiie parent!
npsuo  phwddnu parent!
npsuo  zbgjuk parent!
npsuo  aofkt parent!
uvogit  alicosg parent!
uvogit  iakgro parent!
uvogit  aujqr parent!
zgbzqf  dunscc parent!
zgbzqf  qndcql parent!
zgbzqf  bzbyqoq parent!
zgbzqf  srhcew parent!
xqvmqe  gyrgr parent!
xqvmqe  kkszxy parent!
xqvmqe  mourke parent!
boipij  vtlxs parent!
boipij  uyzpz parent!
wnshgr  avzxg parent!
wnshgr  afjqx parent!
wnshgr  mqgculh parent!
wnshgr  ylmixxx parent!
wnshgr  pzxfm parent!
mvwcdq  myeqz parent!
mvwcdq  fqisabu parent!
zwqgf  obbei parent!
zwqgf  bxdxjoa parent!
zwqgf  xqvmqe parent!
zwqgf  pcqhhy parent!
pmakzzf  funtwzh parent!
pmakzzf  lccukr parent!
vqkwlq  bvrarwr parent!
vqkwlq  ghqvymr parent!
nbbctar  wpdwdep parent!
nbbctar  arhlwh parent!
nvdoenr  coxtcw parent!
nvdoenr  psblh parent!
nvdoenr  foyabk parent!
sdllj  mzbhs parent!
sdllj  wgapb parent!
sdllj  ykavsf parent!
sdllj  mohhap parent!
ghlkk  kqawctp parent!
ghlkk  sgaefd parent!
wiqsy  kzupr parent!
wiqsy  rirch parent!
awpyosw  smbaw parent!
awpyosw  xieqyy parent!
awpyosw  tbute parent!
awpyosw  fwkxcq parent!
stflbsr  yrmifh parent!
stflbsr  eodyisb parent!
stflbsr  jmbptp parent!
bcjpkwf  auulu parent!
bcjpkwf  eeqoiz parent!
bcjpkwf  nmmxms parent!
iieig  elvsrz parent!
iieig  ncqiou parent!
gkgka  xnxcez parent!
gkgka  txmdxj parent!
gkgka  yqlduph parent!
rhqocy  fzerj parent!
rhqocy  myhfh parent!
rhqocy  bqzfjn parent!
lhhlg  wjsijg parent!
lhhlg  szvfc parent!
vrrmn  gqxhfjz parent!
vrrmn  hfgokdn parent!
vrrmn  zfmqgun parent!
vrrmn  dljfl parent!
egcyvrv  cdkadkn parent!
egcyvrv  gvtzws parent!
egcyvrv  zknbqr parent!
qgptpig  jjeci parent!
qgptpig  dpvwrn parent!
kjljvr  qclhx parent!
kjljvr  xqukn parent!
kjljvr  nyaqnau parent!
kjljvr  diupl parent!
euueza  xeyfy parent!
euueza  gybgrld parent!
kupsxf  zxtwo parent!
kupsxf  klvncy parent!
kupsxf  ygbecwq parent!
vxbzw  uosltv parent!
vxbzw  bzjze parent!
vxbzw  owprin parent!
vxbzw  lsxnn parent!
gzoyqay  pjzyj parent!
gzoyqay  bpgbauh parent!
zxtwo  ckaqw parent!
zxtwo  ovcxkye parent!
lvbjtf  kuqnndb parent!
lvbjtf  exuelye parent!
pzxfm  xvteib parent!
pzxfm  gookalb parent!
pzxfm  rpaudj parent!
tfmvb  vlglq parent!
tfmvb  kcscgb parent!
zspohe  jkfnrik parent!
zspohe  iiurfqv parent!
zspohe  wchwgnd parent!
zspohe  xvawgcm parent!
rwrusdg  atkstsn parent!
rwrusdg  efsbeb parent!
rwrusdg  abmlupq parent!
iwcpvdx  kxolyhi parent!
iwcpvdx  xttsj parent!
putdqt  qbvurh parent!
putdqt  rbauepa parent!
putdqt  mhdhb parent!
owhxvku  pnctz parent!
owhxvku  riogbaf parent!
owhxvku  qrpgt parent!
eqsrff  hgyyml parent!
eqsrff  uaxhb parent!
geuopn  fyeqds parent!
geuopn  uqraz parent!
aezwvo  ayvcc parent!
aezwvo  kxsweg parent!
kcekden  pmakzzf parent!
kcekden  fmvdadz parent!
kcekden  zgbzqf parent!
vkmtnn  augxmyy parent!
vkmtnn  fyrauka parent!
ykcmvla  cvgoojy parent!
ykcmvla  codttfw parent!
wgnoil  vpmywt parent!
wgnoil  xjekui parent!
wgnoil  gtdfvuu parent!
wgnoil  cwahmsr parent!
fjiemrs  wcwqeyz parent!
fjiemrs  welid parent!
fjiemrs  sytip parent!
fjiemrs  bmnsk parent!
avzxg  pkeua parent!
avzxg  ubxume parent!
vwqquk  ythoww parent!
vwqquk  sqauq parent!
vwqquk  plevjup parent!
vwqquk  ouxdvp parent!
vwqquk  qtbnqo parent!
vwqquk  kndpli parent!
vwqquk  gvzze parent!
qpafkjx  hxvizze parent!
qpafkjx  klvufp parent!
qpafkjx  txwsp parent!
txfnjo  gwgas parent!
txfnjo  jlryq parent!
ioyiklx  uigot parent!
ioyiklx  ypvews parent!
fwlspf  qpoodx parent!
fwlspf  sxbee parent!
fwlspf  xxiymn parent!
fwlspf  qigsvd parent!
mzhyo  cxodl parent!
mzhyo  aaecklm parent!
mzhyo  imuupp parent!
pbeegf  ztxam parent!
pbeegf  nuyake parent!
rklic  ylfgaps parent!
rklic  gedajwo parent!
rklic  olntlo parent!
rklic  ilsqjz parent!
rklic  tdqxy parent!
rklic  oprsej parent!
wrcpxdx  avsoisf parent!
wrcpxdx  kzzedp parent!
rnjqmh  kzpml parent!
rnjqmh  emdnkj parent!
oilsjpr  pluph parent!
oilsjpr  rmvdiwr parent!
oilsjpr  idgmre parent!
qqktjg  cjxuj parent!
qqktjg  pnmkw parent!
qqktjg  pbeegf parent!
vdpnz  qkzklgx parent!
vdpnz  ywnji parent!
hweub  vdebg parent!
hweub  vcihirs parent!
orulm  dnivyr parent!
orulm  gbcnx parent!
yffid  deiso parent!
yffid  kbtfnu parent!
fyptb  gnbjv parent!
fyptb  rklnuv parent!
fyptb  cxqgvb parent!
zglws  kasnq parent!
zglws  jovgiy parent!
zglws  kywxkgm parent!
zglws  zgrdyl parent!
aikmwxj  bkomu parent!
aikmwxj  pcmimkt parent!
bmhlcgg  yoabvhm parent!
bmhlcgg  mpuhqjm parent!
xlxct  twpxg parent!
xlxct  cxthvz parent!
axlitg  imeyrl parent!
axlitg  waoiyzo parent!
axlitg  hqmxuv parent!
axlitg  spcyi parent!
cmnjg  hhdth parent!
cmnjg  ompzpgp parent!
cmnjg  kdmuzrx parent!
cmnjg  ovvmrux parent!
cmnjg  awpyosw parent!
pcqhhy  pozhxfb parent!
pcqhhy  mohbkpv parent!
pegoi  qsjwlq parent!
pegoi  kxpffcy parent!
pegoi  fwxtdml parent!
pegoi  tfmvb parent!
ljeztky  exqhrl parent!
ljeztky  mcpcxw parent!
ljeztky  hscywgt parent!
plvjk  ksvwjw parent!
plvjk  uglvj parent!
plvjk  rwaeimg parent!
simlhnw  kesgd parent!
simlhnw  ykhrxqf parent!
cakpt  anraget parent!
cakpt  tfpjxcv parent!
cakpt  klzgol parent!
cakpt  ntpmw parent!
crxuc  qiutta parent!
crxuc  ivqduu parent!
crxuc  uvatphy parent!
kxouhtb  aztstf parent!
kxouhtb  qltdv parent!
wdjgdoh  ngvqne parent!
wdjgdoh  zdofuei parent!
wdjgdoh  kqtmc parent!
odzzie  aikmwxj parent!
odzzie  yffid parent!
odzzie  qmhaa parent!
odzzie  ixlern parent!
mibwe  qbdhk parent!
mibwe  mflvlww parent!
mibwe  vvwrg parent!
mibwe  nslyvt parent!
kivlu  hagdjuz parent!
kivlu  stttgb parent!
uxblgk  lcfur parent!
uxblgk  ebfzjux parent!
qshflsm  uhalup parent!
qshflsm  zdncj parent!
oxvcp  ujupo parent!
oxvcp  qsgkmc parent!
qzeljtb  wsuihj parent!
qzeljtb  vlcrx parent!
wugret  zrhyprz parent!
wugret  gwohx parent!
cafxx  zjzxav parent!
cafxx  tcwzc parent!
cafxx  wkjhmcd parent!
otmpv  dopdknn parent!
otmpv  hvjgdxs parent!
otmpv  ydurwqb parent!
mhfci  pegoi parent!
mhfci  ubvvr parent!
mhfci  fqqzx parent!
dqury  iunue parent!
dqury  ffdxovh parent!
qpoodx  gqzczp parent!
qpoodx  adwzzi parent!
qpoodx  ghebwaz parent!
fnlapoh  yxljri parent!
fnlapoh  xlxct parent!
fnlapoh  foldo parent!
mkrrlbv  ahqlq parent!
mkrrlbv  igjmhxe parent!
mkrrlbv  xqdih parent!
mkrrlbv  raormr parent!
bijhyzu  jdvfkii parent!
bijhyzu  chpjfv parent!
bijhyzu  wgnoil parent!
bijhyzu  gkgka parent!
qsjwlq  tzcymqj parent!
qsjwlq  gtzrs parent!
tdqxy  hzrphej parent!
tdqxy  uusufw parent!
tdqxy  wjjsgvw parent!
kfhcuvf  llbsax parent!
kfhcuvf  rckuzt parent!
vetgu  yierd parent!
vetgu  wohob parent!
vetgu  ssbjh parent!
eqpuq  vbkqzje parent!
eqpuq  pcpcm parent!
ustkg  ormhqr parent!
ustkg  xtwtv parent!
iouczne  krivqx parent!
iouczne  xmiygp parent!
foyabk  iieig parent!
foyabk  iejyzgu parent!
foyabk  onwqbz parent!
olqgu  walei parent!
olqgu  bajtat parent!
olqgu  igiqnkc parent!
olqgu  tobzv parent!
olqgu  ocobkpo parent!
olqgu  zglws parent!
xofjd  npznojo parent!
xofjd  twxwtr parent!
xofjd  aqfjqh parent!
ptmqqpk  yejoqrc parent!
ptmqqpk  ihwkjjt parent!
ptmqqpk  fjrrlug parent!
qmhaa  szsfe parent!
qmhaa  nconokw parent!
qmhaa  wenper parent!
qmhaa  tnkptkm parent!
olhbx  zlmvme parent!
olhbx  ljeztky parent!
olhbx  xvpopw parent!
sxcxmg  tcrpymd parent!
sxcxmg  endpyd parent!
sgmbw  ytbnpd parent!
sgmbw  tgqnyb parent!
sgmbw  whgqhb parent!
sgmbw  wustjt parent!
sgmbw  zwwrwfy parent!
tpvcmkz  dtyaj parent!
tpvcmkz  xwmjpb parent!
tpvcmkz  zqkgqs parent!
ctdey  aezwvo parent!
ctdey  vdpnz parent!
ctdey  ruxqapz parent!
gxzgsaa  wcsnr parent!
gxzgsaa  kcvhi parent!
rzvrn  bkzzc parent!
rzvrn  isbppt parent!
rzvrn  ioyiklx parent!
auzdz  fiehsiq parent!
auzdz  eylfls parent!
auzdz  cvkec parent!
auzdz  omkgoai parent!
diila  kthzxmf parent!
diila  kddvj parent!
ojgdow  wdjgdoh parent!
ojgdow  gwgnf parent!
ojgdow  bzznyu parent!
ojgdow  boipij parent!
ojgdow  otmpv parent!
ojgdow  wiqsy parent!
qtbnqo  vlisesb parent!
qtbnqo  olczth parent!
cciwzc  fjcibi parent!
cciwzc  iyrapzn parent!
bzznyu  tggyn parent!
bzznyu  nthusc parent!
gwgnf  wbntjyi parent!
gwgnf  ifmgil parent!
gwgnf  zeximw parent!

zeximw
find-root
dup -2 cells + >name name>string type
CR 0 swap find-balance-weight .

CR
\ ifajhb total-weight CR .
gqmls total-weight CR .
\ sgmbw total-weight CR .
\ ddkhuyg total-weight CR .
\ rhqocy total-weight CR .
jfdck total-weight CR .
marnqj total-weight CR .
upair total-weight CR .
mkrrlbv total-weight CR .
vqkwlq total-weight CR .
wsrmfr total-weight CR .
